### ISSUE TITLE
OpenBSD issues

### ISSUE THREAD

**Issue by Starrcade** [rsu-client/rsu-client#136]
Hello @HikariKnight,
I use OpenBSD 6.2 and i've been working at getting the client to work, however I've ran into some pitfalls;
I managed to install much of the perl modules required, but this one always holds it back;
`WARNING: Running in fallback mode!
rsu-queries will use the system perl so some API calls
may not work until you install certain modules
WARNING: Wx module not found, API calls using WxWidgets will not work

WARNING: Wx::WebView module not found, API calls using Wx::WebView will not work

WARNING: LWP::Simple module not found, API calls using LWP::Simple will either use alternative methods`

My other option was to use the 'java' option by getting the .jar using wget, and then running the following.
`java -cp jagexappletviewer.jar -Dcom.jagex.config=http://YOURWORLDHERE.runescape.com/jav_config.ws -Xms256m -Xmx256m jagexappletviewer .`

After I hit enter though, this is the output.

`No protocol specified
Exception in thread "main" java.awt.AWTError: Can't connect to X11 
window server using ':0' as the value of the DISPLAY variable.
        at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
        at 
sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
        at 
sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)
        at java.security.AccessController.doPrivileged(Native Method)
        at 
sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at 
java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
        at 
java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
        at java.awt.Window.initGC(Window.java:475)
        at java.awt.Window.init(Window.java:495)
        at java.awt.Window.<init>(Window.java:537)
        at java.awt.Frame.<init>(Frame.java:420)
        at java.awt.Frame.<init>(Frame.java:385)
        at app.appletviewer.a(appletviewer.java:507)
        at jagexappletviewer.main(jagexappletviewer.java:34)`

I think there could be a way to do this, I just need to know what to fix/install. Maybe even see if Flatpak for BSD exists or if the 'java wrapper' browser plugin would actually work.

**Comment by HikariKnight** [comment]
not sure if BSD uses X11 or not anymore but thats the error, failing to display the window on the Display :0 in the X11 window server
