### ISSUE TITLE
Random crashes and "illegal operations"

### ISSUE THREAD

**Issue by annadane** [rsu-client/rsu-client#138]
On Debian Sid. Application keeps crashing in random places (once in Barrows, once in Taverly dungeon). Here's my output:

 Executing the RuneScape Client!
You are now in the hands of Jagex.

######## Jagex client output will appear below here ########

Trying to load icon file: /home/annadane/Runescape/rsu-client-master/runescape/share/img/RuneScape3/jagexappletviewer.png
Loader init
Init 1
Init 2
Init 3
Init 4
Init 5
Init 6
Init 7
Init 8
Loader show
Loader set message
Config url:http://www.runescape.com/k=3/l=0/jav_config.ws
Config URL is http://www.runescape.com/k=3/l=0/jav_config.ws
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by app.u (file:/home/annadane/Runescape/rsu-client-master/runescape/bin/jagexappletviewer.jar) to field java.lang.ClassLoader.scl
WARNING: Please consider reporting this to the maintainers of app.u
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Error: client.init:1145 java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke:62 java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke:43 java.base/java.lang.reflect.Method.invoke:564 Rs2Applet.a:212 Rs2Applet.init:583 app.appletviewer.a:846 jagexappletviewer.main:34 | java.lang.RuntimeException | 
sun.awt.image.ImageFormatException: Unsupported color conversion request
	at java.desktop/sun.awt.image.JPEGImageDecoder.readImage(Native Method)
	at java.desktop/sun.awt.image.JPEGImageDecoder.produceImage(JPEGImageDecoder.java:141)
	at java.desktop/sun.awt.image.InputStreamImageSource.doFetch(InputStreamImageSource.java:269)
	at java.desktop/sun.awt.image.ImageFetcher.fetchloop(ImageFetcher.java:212)
	at java.desktop/sun.awt.image.ImageFetcher.run(ImageFetcher.java:176)
document.cookie="settings=Ymi9Liy-EKCk5P1bdK3YjRQaY5OInAxj-tHELINO7uY; version=1; path=/; domain=.runescape.com; Expires=Mon 15-Mar-2021 18:04:12 GMT; Max-Age=94608000"
Error: anb.l() abs.i() client.fe() client.fz() client.au() sb.g() sb.v() | java.base/java.util.ImmutableCollections.uoe:71 java.base/java.util.ImmutableCollections$AbstractImmutableList.addAll:78 anb.l:32 abs.i:20 client.fe:1845 client.fz:1804 client.au:1456 sb.g:573 sb.v:549 sb.run:506 java.base/java.lang.Thread.run:844 | java.lang.UnsupportedOperationException |  2832,9744,104,104 0,2886,9795 1 0 2 1600,791 1 1 0 1 0 0 504 3 7924 VQyG-oz9TnBERxLr3rn3YlZ96JmfVRwK
error_game_crash

**Comment by annadane** [comment]
@HikariKnight

**Comment by HikariKnight** [comment]
never seen those warnings before
and i cant suggest anything else for that crash other than to try a different version of java @annadane 
as i am not sure if they are related to the graphic card driver or not

**Comment by RyoshiKayo** [comment]
We can try and help as much as possible but anything below `######## Jagex client output will appear below here ########` is output from the Jagex client, which Jagex has said before that they will only support the provided clients on the downloads page.

**Comment by annadane** [comment]
Okay; so you can fix this by changing, in rsu-client-master/runescape/share/configs/settings.conf, preferredjava=/usr/lib/jvm/java-8-openjdk-amd64/bin/java (obviously do actually install Java 8 first, in Debian I installed both openjdk-8-jdk and openjdk-8-jre just to be sure but you possibly don't need both)
